### ISSUE TITLE
The documentation links are broken

### ISSUE THREAD

**Issue by yayawar** [wpdrift/WP-Restaurant-Listings#1]
All the links for documentation go to a 404 page. Pls update the links.

**Comment by kish2011** [comment]
@yayawar Sorry we are on it. Documentation is not yet ready too. We will update in 1 week. Well after installing it has really a cool wizard so you do not need to anything. Thanks.

**Comment by yayawar** [comment]
Yes, the wizard works like a charm. :)

On another note, if I've opted for No Account Requirement and No User creation while submitting a restaurant, the Post a Restaurant page shouldn't show a Sign In icon/message

**Comment by kish2011** [comment]
Thanks for the feedback. Are you doing a listing site

**Comment by yayawar** [comment]
Yes. Creating a listing and review which is part of the http://www.greatindianfoodtrip.com. So the idea is to list down the places that are visited as part of #GreatIndianFoodTrip which people can later refer to and visit.

**Comment by yayawar** [comment]
The plugin's JS & CSS are conflicting with the Event Pro theme by Theme Freesia. The moment I enable the plugin, the homepage slider goes for a toss! Working fine on other default WP themes.

**Comment by kish2011** [comment]
@yayawar please check with theme developer as we are making for all defat themes like 2015,2017 etc. We can not give time for premium themes. Most of the premium themes adds extra css/js. So conflict happens.

**Comment by yayawar** [comment]
Yes. Already flagged with them. I do understand the pains of creating a plugin and releasing it for consumption. Cheers!

**Comment by kish2011** [comment]
@yayawar let me know in which site you are using it and how it it helpful :)

**Comment by yayawar** [comment]
As I mentioned earlier, I was intending to get it to work on http://greatindianfoodtrip.com. However, due to conflict with the theme, I've abandoned the plan (since the theme support also has ended, being a premium theme). Will see if I can customize the theme later in leisure.

**Comment by kish2011** [comment]
@yayawar you can try this theme https://themeforest.net/item/listify-wordpress-directory-theme/9602611 , If you have budget you can hire us.

**Comment by kish2011** [comment]
@yayawar we have fixed. Here is the documentation link https://wpdrift.com/docs/article-categories/getting-started/
